name: publish

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install cargo components
        run: rustup component add clippy

      - name: login to crates.io
        run: cargo login ${{ secrets.CRATESIO }}

      - name: publish to crates.io
        run: cargo clippy --all-targets --all-features -- -D warnings && cargo test && cargo publish
